gregwar_test:
    resource: "@GregwarTestBundle/Controller/"
    type:     annotation
    prefix:   /

gregwar_captcha_routing:
        resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
